### ISSUE TITLE
Publish to Ansible Galaxy

### ISSUE THREAD

**Issue by rorychatterton** [dev-sec/ansible-windows-hardening#7]
**Is your feature request related to a problem? Please describe.**
Today only the Linux configurations are published to Ansible Galaxy under the dev-sec community provider: https://galaxy.ansible.com/dev-sec

**Describe the solution you'd like**
It would be good to see the Windows Hardening playbook published in Galaxy.

**Comment by rndmh3ro** [comment]
Hey @rorychatterton,

you're right, we don't have any released version on Galaxy or here on Github, yet. That's because this role is not actually done.
We still have to implement all baseline-checks from https://github.com/dev-sec/windows-baseline and add some proper automation with travis/circleci.

Before this happens I don't want to create a release.

Are you open to help working on the role? :)

**Comment by rorychatterton** [comment]
Ah right! That wasn't clear off the readme :D (Admittedly I hadn't tried to run or inspec it yet)

Ansible Tower usage is something I will need to help bootstrap at my new org - more than happy to help contribute back up, although possibly not for a fortnight or so.

**Comment by rndmh3ro** [comment]
Hey @rorychatterton, you're right that the readme was not clear on this. I added some more information into it to make it clear that the role is not yet ready for securing your servers.

You're very welcome to contribute and if you'll need help, just raise an issue!
